### ISSUE TITLE
Groups

### ISSUE THREAD

**Issue by adamamyl** [no2id/speccing#1]
NO2ID apparently has 118 published local groups:

```sql
mysql> select count(*) from localgroups where no_web=0;
+----------+
| count(*) |
+----------+
|      118 |
+----------+
```
scattered around the UK (-1: international). Not all of these may be active.

For each group, on the (ancient) website we should display:
 - the groupname
 - the co-ordinators' name, and linking to their @no2id.net email address
 - their mailing/discussion list
 - their website (if they have one)
 - their phone number, if that's available to the public

What else should we include? If anything? Do any have social media links?

In the past, we've used a database table to not only feed the website (although the website was converted into a static dump), but also the **email system** whereby Fred Flintstone (fred@flintstone.net) is the co-ordinator for Bumptown, bumptown@no2id.net redirects to fred@flintstone.net. For the new Wordpres site, do we go with Wordpress pulling the necessary information from our MySQL database table (in a custom page type?), or do we use another technique, like a custom page, and risk things being duplicated/falling out of sync?

**Comment by adamamyl** [comment]
- [ ] Manchester
- [ ] Edinburgh
- [ ] Glasgow
- [ ] London/Camden

**Comment by adamamyl** [comment]
This is currently handled through custom metadata / a custom content type, which is displayed through the front end viz https://github.com/no2id/custom-fields-table-display

**Comment by adamamyl** [comment]
Supported fields are:

 - name
 - region
 - coordinator's name
 - public phone number
 - group email address
 - mailing list URL
 - twitter
 - instagram
 - facebook

**Comment by jamesdbaker1** [comment]
I think we should add Dover to the active groups, Ian down there still answers emails and very rarley posts to @DoverNO2ID having any twitter links to groups would be nice.

I know of @ManchesterNO2ID as the other one.
