### ISSUE TITLE
Set-up Sendy

### ISSUE THREAD

**Issue by adamamyl** [no2id/speccing#5]
- [x] Purchase license
- [x] Set-up AWS account for SES
- [x] Deploy to Linode
- [x] Config setup
- [x] Create template campaigns etc (avec campaigns@)
- [x] Import users
- [x] Setup Wordpress Extension

**Comment by jamesdbaker1** [comment]
Hi Adam, how are we doing on this now?

**Comment by adamamyl** [comment]
this was done as part of launch.
